project:
  type: book
  output-dir: ..\ml-r\

book:
  title: "Основи машинного навчання в R"
  subtitle: "Навчальний посібник з курсу **Прикладне математичне моделювання в `R`** для студентів спеціальності економічна кібернетика, фінанси та кредит, 3 курс"
  author: "Юрій Клебан"
  date: "`r Sys.Date()`"
  date-format: short
  google-analytics: ""
  cover-image: img/cover.png
  site-url: https://kleban.github.io/ml-r/
  repo-url: https://github.com/kleban/ml-r/
  repo-branch: main
  sharing: [twitter, facebook, linkedin]
  favicon: img/favicon.png
  chapters:
    - index.qmd
    - 00-intro.qmd
    - 010-intro.qmd
    - part: 020-feature-engeneering.qmd
      chapters:
        - 023-feature-engeneering-woe-binning.ipynb
    - part: 030-supervised-learning.qmd
      chapters:        
        - 031-supervised-learning-linear-regression-1.ipynb
        - 032-supervised-learning-linear-regression-2.ipynb
        - 033-supervised-learning-desicion-trees-regression.ipynb
        - 034-supervised-learning-neutal-networks-regression.ipynb
        - 035-supervised-learning-logistic-regression.ipynb
        - 036-supervised-learning-desicion-trees-classification.ipynb
        - 037-supervised-learning-neural-network-classification.ipynb
    - part: 040-unsupervised-learning.qmd
      chapters:
        - 041-unsupervised-learning-clustering-kmeans-1.ipynb
        - 042-unsupervised-learning-clustering-kmeans-2.ipynb
        - 043-unsupervised-learning-clustering-kmeans-and-random-forest.ipynb
    - references.qmd
  page-navigation: true
  page-footer: "Copyright 2023, Юрій Клебан" 
    
language: _language-ua.yml 

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: img/cover.png
    code-link: true
    css: css/style.css
    number-sections: true
    toc: true
    highlight-style: github
    code-line-numbers: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true

crossref:
  tbl-title: 'Таблиця'
  lst-title: 'Лістинг'
  fig-title: 'Рис.'
  fig-labels: arabic
  title-delim: "."



